name: 'Publish Test Report'
on:
  workflow_run:
    workflows: ['ci-pr', 'ci-master']  # runs after workflows
    types:
      - completed
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'ID of the workflow run to download artifacts from.'
        required: true
        default: ''

permissions:
  contents: read
  actions: read
  checks: write

jobs:

  publish-reports-v5x:
    uses: ./.github/workflows/shared-publish-report.yml
    with:
      versions: '["v5.1.1"]'
      godot-versions: '["4.3", "4.4", "4.4.1"]'
      workflow-run-id: ${{ github.event.inputs.workflow_run_id || github.event.workflow_run.id }}

  publish-reports-v61:
    uses: ./.github/workflows/shared-publish-report.yml
    with:
      versions: '["v6.0.0"]'
      godot-versions: '["4.5", "4.5.1"]'
      workflow-run-id: ${{ github.event.inputs.workflow_run_id || github.event.workflow_run.id }}

  publish-reports-v62:
    uses: ./.github/workflows/shared-publish-report.yml
    with:
      versions: '["v6.1.0", "latest"]'
      godot-versions: '["4.5", "4.5.1", "4.6", "4.6.1", "4.6.2"]'
      workflow-run-id: ${{ github.event.inputs.workflow_run_id || github.event.workflow_run.id }}
